import { ListingCommentKind } from 'db';
import { z } from 'zod';

/**
 * Shared input schemas for the share-page server actions. Kept in a
 * plain (non-`'use server'`) module so sibling action files can
 * import them, and so we have a single place to tweak error
 * messages / validation rules. All share-token actions accept a
 * `token` (UUID v4 string as generated by `crypto.randomUUID`),
 * every owner-scoped action accepts a `tripId` (Prisma cuid).
 */

export const tripIdSchema = z.object({
  tripId: z.string().cuid('A valid trip id is required.'),
});

export const updatePublishedTripSettingsSchema = tripIdSchema
  .extend({
    votingOpen: z.boolean().optional(),
    commentsOpen: z.boolean().optional(),
    allowGuestSuggestions: z.boolean().optional(),
  })
  .refine(
    (value) =>
      typeof value.votingOpen !== 'undefined' ||
      typeof value.commentsOpen !== 'undefined' ||
      typeof value.allowGuestSuggestions !== 'undefined',
    { message: 'No published trip settings were provided.' },
  );

export const guestNameSchema = tripIdSchema.extend({
  displayName: z.string().trim().min(1, 'Guest name is required.').max(50, 'Guest name is too long.'),
});

export const removeGuestSchema = tripIdSchema.extend({
  guestId: z.string().cuid('A valid guest id is required.'),
});

export const moderateCommentSchema = tripIdSchema.extend({
  commentId: z.string().cuid('A valid comment id is required.'),
  hidden: z.boolean(),
});

export const publishedGuestSessionSchema = z.object({
  token: z.string().uuid('A valid published trip link is required.'),
  guestId: z.string().cuid('A valid guest id is required.'),
});

export const castVoteSchema = z.object({
  token: z.string().uuid('A valid published trip link is required.'),
  guestId: z.string().cuid('A valid guest id is required.'),
  listingId: z.string().cuid('A valid listing id is required.'),
});

export const submitListingSchema = z.object({
  token: z.string().uuid('A valid published trip link is required.'),
  guestId: z.string().cuid('A valid guest id is required.'),
  url: z.string().url('A valid listing URL is required.'),
});

const optionalNullableInt = z.union([z.number().int(), z.null()]).optional();

export const updateListingDetailsSchema = z
  .object({
    token: z.string().uuid('A valid published trip link is required.'),
    guestId: z.string().cuid('A valid guest id is required.'),
    listingId: z.string().cuid('A valid listing id is required.'),
    price: optionalNullableInt,
    bedroomCount: optionalNullableInt,
    bedCount: optionalNullableInt,
    bathroomCount: optionalNullableInt,
    notes: z.string().trim().max(5000, 'Notes are too long.').nullable().optional(),
  })
  .refine(
    (value) =>
      typeof value.price !== 'undefined' ||
      typeof value.bedroomCount !== 'undefined' ||
      typeof value.bedCount !== 'undefined' ||
      typeof value.bathroomCount !== 'undefined' ||
      typeof value.notes !== 'undefined',
    { message: 'At least one field must be provided.' },
  );

export const addCommentSchema = z.object({
  token: z.string().uuid('A valid published trip link is required.'),
  guestId: z.string().cuid('A valid guest id is required.'),
  listingId: z.string().cuid('A valid listing id is required.'),
  kind: z.enum(ListingCommentKind),
  body: z.string().trim().min(1, 'Comment is required.').max(1000, 'Comment is too long.'),
});
